### ISSUE TITLE
Avoid duplicates from the same user

### ISSUE THREAD

**Issue by raboof** [JulienMalka/nix-hash-collection#12]
Should we allow the same user to submit the same hash twice? Maybe ignore those?

**Comment by JulienMalka** [comment]
Tough question: Ideally the report for a derivation should reflect in what proportion the hashes have been obtained for a specific output. By doing that we break that property I think. What we could do is allow only one report for each user. We do not capture flaky builds in that scenario but probably with large numbers we do.

**Comment by raboof** [comment]
I agree, it depends on the use case whether it makes sense to count the same hash from the same user - so let's allow submitting it
