### ISSUE TITLE
share rebuilds recording nondeterminism

### ISSUE THREAD

**Issue by raboof** [JulienMalka/nix-hash-collection#14]
When using `nix-build --check` or `nix build --rebuild`, successful rebuilds will be passed to the post-build-hook, but unsuccessful rebuilds are not.

Perhaps we could define a `diff-hook` that shares the rebuild result in this case?

**Comment by JulienMalka** [comment]
Do you mean unsuccessful rebuilds as build failed or as build gave a different output than the one in cache.nixos.org ?

**Comment by raboof** [comment]
builds that gave a different output than the one already on the system

**Comment by JulienMalka** [comment]
I agree that having a diff-hook is a good idea.

**Comment by JulienMalka** [comment]
The difficulty with the diff-hook is that if I am not mistaken the diff-hook is called only with the first output that failed reproducibility check. The post-build-hook is not called for succeeding outputs, the process is stopped as soon as nix detects *one* non-reproducible output.

**Comment by raboof** [comment]
Good point - and yes, that matches what I see.

So this means:
* matching rebuilds are under-counted (successful builds that also have a failed output are missed)
* mismatching rebuilds are under-counted (in the case that a derivation has multiple mismatching outputs, only one is reported)
While not ideal, I think those are limitations we can live with for now?

**Comment by JulienMalka** [comment]
I think we can experiment and see how skewed our results are. I'll also try to see if we can try to improve things on Nix's side.
