### ISSUE TITLE
Difference with `trustix`?

### ISSUE THREAD

**Issue by thufschmitt** [JulienMalka/nix-hash-collection#24]
i just came across this project (though https://github.com/NixOS/nix/pull/10101 – which has a cool issue number btw), and I'm curious how it compare to https://github.com/nix-community/trustix which seems to have a similar goal of improving the trust on the Nix build packages

**Comment by raboof** [comment]
Good question! The overarching goal indeed overlaps somewhat, but trustix is more ambitious: with this project, we aim to have something simple in the short term, just basically CRUD collection of hashes and some simple scripts around it.

trustix has a more elaborate design with multiple transparency logs that are self-hosted by the attesters, and supports more advanced use cases like showing the aggregating system is not 'lying by omission' and perhaps that submitters aren't providing contradicting statements.

Let's keep this issue open until we've properly explained this in the README.
