### ISSUE TITLE
model: record output path?

### ISSUE THREAD

**Issue by raboof** [JulienMalka/nix-hash-collection#5]
might be worth collecting as it's easy to determine when you've built the derivation, but not necessarily afterwards

**Comment by JulienMalka** [comment]
I believe we already have that, look for example the output of  `http://localhost:8000/derivation/agml7yvlgmdhlbm9a9kw253j2mbyz139-curl-8.6.0`

```json
{
  "/nix/store/2hapkajcapp9vzwrlj58jwsrjpr4vj70-curl-8.6.0": {
    "1gg83mlx95xx6wi8pkvwzmjpm8m7zsjy0cibmcx6lx41gbpggjhz": 1
  },
  "/nix/store/wfdx6m40yxvw73pdf5w8dsww9y1z6l7y-curl-8.6.0-man": {
    "1wf0j69qvy0glqn77janyh10m75qdy67vlb8vmgn97aq88g8r53g": 1
  },
  "/nix/store/x23aqwc39pp4zx5iiz0mqyh5mnvrz43z-curl-8.6.0-bin": {
    "0v8dhh0hz31yhg9a0b3hqnrhg3v8p4sp078aqb9s8gs7xi7c60f4": 1
  }
}
```
Is that what you meant ?

**Comment by raboof** [comment]
ah, indeed - so `output_name` contains the output path. might be slightly clearer to rename that to output_path?
